# Generated by Django 5.1.6 on 2025-02-16 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmedConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название военного конфликта')),
            ],
            options={
                'verbose_name': 'Военный конфликт',
                'verbose_name_plural': 'Военные конфликты',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', verbose_name='Файлы')),
                ('title', models.CharField(max_length=100, verbose_name='Название файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название медали')),
                ('image', models.ImageField(upload_to='medals/', verbose_name='Изображение медали')),
            ],
            options={
                'verbose_name': 'Медаль',
                'verbose_name_plural': 'Медали',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_of_birth', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('military_commissariat', models.CharField(max_length=255, verbose_name='Наименование военного комиссариата')),
                ('military_rank', models.CharField(max_length=100, verbose_name='Воинское звание')),
                ('date_of_death', models.DateField(verbose_name='Дата гибели или смерти')),
                ('burial_place', models.CharField(max_length=255, verbose_name='Место захоронения')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано?')),
                ('armed_conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.armedconflict', verbose_name='Конфликт')),
                ('files', models.ManyToManyField(blank=True, to='person.files', verbose_name='Доп. файлы')),
                ('medals', models.ManyToManyField(blank=True, to='person.medals', verbose_name='Награды')),
            ],
            options={
                'verbose_name': 'Боец',
                'verbose_name_plural': 'Бойцы',
            },
        ),
    ]
