# Generated by Django 5.1.6 on 2025-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmedConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название военного конфликта')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_of_birth', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('military_commissariat', models.CharField(max_length=255, verbose_name='Наименование военного комиссариата')),
                ('military_rank', models.CharField(max_length=100, verbose_name='Воинское звание')),
                ('awards', models.TextField(verbose_name='Награды')),
                ('date_of_death', models.DateField(verbose_name='Дата гибели или смерти')),
                ('burial_place', models.CharField(max_length=255, verbose_name='Место захоронения')),
                ('biography_facts', models.TextField(blank=True, null=True, verbose_name='Иные факты биографии')),
                ('conflicts_participated', models.ManyToManyField(to='person.armedconflict')),
            ],
            options={
                'verbose_name': 'Боец',
                'verbose_name_plural': 'Бойцы',
            },
        ),
    ]
