# Generated by Django 5.1.6 on 2025-02-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='conflicts_participated',
        ),
    ]
