# Generated by Django 5.1.6 on 2025-02-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_conflicts_participated'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='conflicts_participated',
            field=models.ManyToManyField(blank=True, null=True, to='person.armedconflict', verbose_name='Конфликты'),
        ),
    ]
