# Generated by Django 5.1.6 on 2025-02-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_conflicts_participated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название медали')),
                ('image', models.ImageField(upload_to='medals/', verbose_name='Изображение медали')),
            ],
            options={
                'verbose_name': 'Медаль',
                'verbose_name_plural': 'Медали',
            },
        ),
        migrations.AlterModelOptions(
            name='armedconflict',
            options={'verbose_name': 'Военный конфликт', 'verbose_name_plural': 'Военные конфликты'},
        ),
        migrations.AlterField(
            model_name='person',
            name='conflicts_participated',
            field=models.ManyToManyField(blank=True, to='person.armedconflict', verbose_name='Конфликты'),
        ),
    ]
