# Generated by Django 5.1.6 on 2025-02-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_logging_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='card_item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID на карте'),
        ),
    ]
