# Generated by Django 5.1.6 on 2025-02-15 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_medals_alter_armedconflict_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='conflicts_participated',
        ),
        migrations.AddField(
            model_name='person',
            name='conflicts_participated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.armedconflict', verbose_name='Конфликты'),
        ),
    ]
