# Generated by Django 5.1.6 on 2025-02-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_photo_remove_person_conflicts_participated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='awards',
        ),
        migrations.AddField(
            model_name='person',
            name='medals',
            field=models.ManyToManyField(to='person.medals', verbose_name='Награды'),
        ),
    ]
