# Generated by Django 5.1.6 on 2025-02-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_remove_person_awards_person_medals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='conflicts_participated',
            new_name='armed_conflict',
        ),
    ]
