# Generated by Django 5.1.6 on 2025-02-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_rename_conflicts_participated_person_armed_conflict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='biography_facts',
            new_name='biography',
        ),
    ]
