# Generated by Django 5.1.6 on 2025-02-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_files_alter_person_biography_person_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
    ]
