# Generated by Django 5.1.6 on 2025-02-16 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_alter_person_armed_conflict_alter_person_medals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='armed_conflict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.armedconflict', verbose_name='Конфликт'),
            preserve_default=False,
        ),
    ]
